root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

plugins:
  - expandable-chapters
  - search
  - copy-code-button
  - theme-default
  - back-to-top-button
  - github
  - splitter
  - toc

pluginsConfig:
  github:
    url: https://github.com/your-repo/fpga_tutorial
  theme-default:
    showLevel: true
  toc:
    addClass: true
    className: toc

variables:
  themeColor: "#3f51b5"
  themeColorSecondary: "#ff4081" 